version = 1
SPDX-PackageName = "OrientDB"
SPDX-PackageSupplier = "info@orientdb.dev"
SPDX-PackageDownloadLocation = "https://github.com/orientechnologies/orientdb"
SPDX-PackageComment = "The code in this licensed by OrientDB"

[[annotations]]
path = "**/.gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/pom.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/src/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/script/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/config/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/META-INF/MANIFEST.MF"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/plugins/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "distribution/docker/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "lucene/README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/.mvn/jvm.config"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "CONTRIBUTING.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "_base/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "pom.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "Jenkinsfile"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "Jenkinsfile-crash.groovy"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "license.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "history.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "readme.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".gitattributes"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "OrientDB_logo.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "mvnw"
precedence = "aggregate"
SPDX-FileCopyrightText = "Apache Software Foundation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "mvnw.cmd"
precedence = "aggregate"
SPDX-FileCopyrightText = "Apache Software Foundation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".mvn/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Apache Software Foundation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/assembly/archive.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/build.sh"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/helpers.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/**.conf.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/yarn.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/webpack.config.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/test/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/.jshintrc"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/.editorconfig"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "studio/CHANGELOG.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/driver/src/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/driver/pom.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/distribution/src/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/distribution/config/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/distribution/docker/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/distribution/pom.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/server/src/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/server/pom.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/server/.gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/pom.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/.gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/tests-scala/src/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/tests-scala/config/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/tests-scala/project/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gremlin/tests-scala/build.sbt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 OrientDB"
SPDX-License-Identifier = "Apache-2.0"
