/* Generated By:JJTree: Do not edit this line. OCreateClusterStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.Map;

public class OCreateClusterStatement extends OStatement {

  /**
   * Class name
   */
  protected OIdentifier name;

  protected OInteger id;

  protected boolean blob = false;

  public OCreateClusterStatement(int id) {
    super(id);
  }

  public OCreateClusterStatement(OrientSql p, int id) {
    super(p, id);
  }

  @Override public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("CREATE ");
    if (blob) {
      builder.append("BLOB ");
    }
    builder.append("CLUSTER ");
    name.toString(params, builder);
    if (id != null) {
      builder.append(" ID ");
      id.toString(params, builder);
    }
  }

  @Override public OCreateClusterStatement copy() {
    OCreateClusterStatement result = new OCreateClusterStatement(-1);
    result.name = name == null ? null : name.copy();
    result.id = id == null ? null : id.copy();
    result.blob = blob;
    return result;
  }
}
/* JavaCC - OriginalChecksum=6011a26678f2175aa456a0a6c094cb13 (do not edit this line) */
