/* Generated By:JJTree: Do not edit this line. ODeleteVertexStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.Map;

public class ODeleteVertexStatement extends OStatement {

  protected OFromClause  fromClause;
  protected OWhereClause whereClause;
  protected boolean      returnBefore = false;
  protected OLimit       limit        = null;
  protected OBatch       batch        = null;

  public ODeleteVertexStatement(int id) {
    super(id);
  }

  public ODeleteVertexStatement(OrientSql p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
    StringBuilder result = new StringBuilder();
    result.append("DELETE VERTEX ");
    result.append(fromClause.toString());
    if (returnBefore) {
      result.append(" RETURN BEFORE");
    }
    if (whereClause != null) {
      result.append(" WHERE ");
      result.append(whereClause.toString());
    }
    if (limit != null) {
      result.append(limit);
    }
    if (batch != null) {
      result.append(batch);
    }
    return result.toString();
  }

  public void replaceParameters(Map<Object, Object> params) {
    fromClause.replaceParameters(params);

    if (whereClause != null) {
      whereClause.replaceParameters(params);
    }

    if (limit != null) {
      limit.replaceParameters(params);
    }
    if (batch != null) {
      batch.replaceParameters(params);
    }

  }
}
/* JavaCC - OriginalChecksum=b62d3046f4bd1b9c1f78ed4f125b06d3 (do not edit this line) */
