/* Generated By:JJTree: Do not edit this line. OFromItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.List;
import java.util.Map;

public class OFromItem extends SimpleNode {

  protected List<ORid>          rids;
  protected OCluster            cluster;
  protected OIdentifier         className;
  protected OIndexIdentifier    index;
  protected OMetadataIdentifier metadata;
  protected OStatement          statement;
  protected OInputParameter     inputParam;

  private static final Object   UNSET           = new Object();
  private Object                inputFinalValue = UNSET;

  public OFromItem(int id) {
    super(id);
  }

  public OFromItem(OrientSql p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  @Override
  public String toString(String prefix) {
    if (rids != null && rids.size() > 0) {
      if (rids.size() == 1) {
        return rids.get(0).toString();
      } else {
        StringBuilder builder = new StringBuilder();
        builder.append("[");
        boolean first = true;
        for (ORid rid : rids) {
          if (!first) {
            builder.append(", ");
          }
          builder.append(rid.toString());
          first = false;
        }
        builder.append("]");
        return builder.toString();
      }
    } else if (cluster != null) {
      return cluster.toString();
    } else if (className != null) {
      return className.getValue();
    } else if (metadata != null) {
      return metadata.toString();
    } else if (statement != null) {
      return "(" + statement.toString() + ")";
    } else if (index != null) {
      return index.toString();
    } else if (inputParam != null) {
      if (inputFinalValue == UNSET) {
        return inputParam.toString();
      } else if (inputFinalValue == null) {
        return "NULL";
      } else {
        if (inputFinalValue instanceof String) {
          inputFinalValue = ((String) inputFinalValue).replaceAll(" ", "");// avoid SQL injection, temporary patch
        }
        return inputFinalValue.toString();
      }
    }

    return super.toString();
  }

  @Override
  public String toString() {
    return toString("");
  }

  public void replaceParameters(Map<Object, Object> params) {
    if (statement != null) {
      statement.replaceParameters(params);
    }
    if (inputParam != null) {
      Object result = inputParam.bindFromInputParams(params);
      if (inputParam != result) {
        inputFinalValue = result;
      }
    }
  }
}
/* JavaCC - OriginalChecksum=f64e3b4d2a2627a1b5d04a7dcb95fa94 (do not edit this line) */
