/* Generated By:JJTree: Do not edit this line. OMatchExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class OMatchExpression extends SimpleNode {
  protected OMatchFilter origin;
  protected List<OMatchPathItem> items = new ArrayList<OMatchPathItem>();

  public OMatchExpression(int id) {
    super(id);
  }

  public OMatchExpression(OrientSql p, int id) {
    super(p, id);
  }

  public void toString(Map<Object, Object> params, StringBuilder builder) {
    origin.toString(params, builder);
    for (OMatchPathItem item : items) {
      item.toString(params, builder);
    }
  }

  public void toGenericStatement(StringBuilder builder) {
    origin.toGenericStatement(builder);
    for (OMatchPathItem item : items) {
      item.toGenericStatement(builder);
    }
  }

  @Override
  public OMatchExpression copy() {
    OMatchExpression result = new OMatchExpression(-1);
    result.origin = origin == null ? null : origin.copy();
    result.items =
        items == null ? null : items.stream().map(x -> x.copy()).collect(Collectors.toList());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    OMatchExpression that = (OMatchExpression) o;

    if (origin != null ? !origin.equals(that.origin) : that.origin != null) return false;
    if (items != null ? !items.equals(that.items) : that.items != null) return false;

    return true;
  }

  @Override
  public int hashCode() {
    int result = origin != null ? origin.hashCode() : 0;
    result = 31 * result + (items != null ? items.hashCode() : 0);
    return result;
  }

  public OMatchFilter getOrigin() {
    return origin;
  }

  public void setOrigin(OMatchFilter origin) {
    this.origin = origin;
  }

  public List<OMatchPathItem> getItems() {
    return items;
  }

  public void setItems(List<OMatchPathItem> items) {
    this.items = items;
  }

  public void addItem(OMatchPathItem item) {
    this.items.add(item);
  }
}
/* JavaCC - OriginalChecksum=73491fb653c32baf66997290db29f370 (do not edit this line) */
