/* Generated By:JJTree: Do not edit this line. OMetadataIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.Map;

public class OMetadataIdentifier extends SimpleNode {

  protected String name;

  public OMetadataIdentifier(int id) {
    super(id);
  }

  public OMetadataIdentifier(OrientSql p, int id) {
    super(p, id);
  }

  /**
   * Accept the visitor.
   **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append("metadata:");
    builder.append(name);
  }

  public String getName() {
    return name;
  }

  public OMetadataIdentifier copy() {
    OMetadataIdentifier result = new OMetadataIdentifier(-1);
    result.name = name;
    return result;
  }
}
/* JavaCC - OriginalChecksum=85e179b9505270f0596904070fdf0745 (do not edit this line) */
