/* Generated By:JJTree: Do not edit this line. OparseAdminStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.Map;

public class OparseAdminStatement extends SimpleNode {
  public OparseAdminStatement(int id) {
    super(id);
  }

  public OparseAdminStatement(OrientSql p, int id) {
    super(p, id);
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {}

  @Override
  public void toString(Map<Object, Object> params, StringBuilder builder) {}
}
/* JavaCC - OriginalChecksum=11c6788445137ecd7562c11c62bba493 (do not edit this line) */
