/* Generated By:JJTree: Do not edit this line. OResourcePathItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.Map;

public class OResourcePathItem extends SimpleNode {
  protected boolean star = false;
  protected OIdentifier identifier;
  protected String      name;

  public OResourcePathItem(int id) {
    super(id);
  }

  public OResourcePathItem(OrientSql p, int id) {
    super(p, id);
  }

  @Override public void toString(Map<Object, Object> params, StringBuilder builder) {
    if (star) {
      builder.append("*");
    } else if (identifier != null) {
      identifier.toString(params, builder);
    } else {
      builder.append(name);
    }
  }

  @Override public OResourcePathItem copy() {
    OResourcePathItem result = new OResourcePathItem(-1);
    result.star = star;
    result.identifier = identifier == null ? null : identifier.copy();
    result.name = name;
    return result;
  }

  @Override public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;

    OResourcePathItem that = (OResourcePathItem) o;

    if (star != that.star)
      return false;
    if (identifier != null ? !identifier.equals(that.identifier) : that.identifier != null)
      return false;
    if (name != null ? !name.equals(that.name) : that.name != null)
      return false;

    return true;
  }

  @Override public int hashCode() {
    int result = (star ? 1 : 0);
    result = 31 * result + (identifier != null ? identifier.hashCode() : 0);
    result = 31 * result + (name != null ? name.hashCode() : 0);
    return result;
  }
}
/* JavaCC - OriginalChecksum=b90ccdd61b6adcd40cde2adee353e89f (do not edit this line) */
