/* Generated By:JavaCC: Do not edit this line. OrientSqlTreeConstants.java Version 5.0 */
package com.orientechnologies.orient.core.sql.parser;

public interface OrientSqlTreeConstants
{
  public int JJTRID = 0;
  public int JJTPARSE = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTINTEGER = 3;
  public int JJTFLOATINGPOINT = 4;
  public int JJTNUMBER = 5;
  public int JJTSTATEMENT = 6;
  public int JJTSELECTWITHOUTTARGETSTATEMENT = 7;
  public int JJTSELECTSTATEMENT = 8;
  public int JJTTRAVERSESTATEMENT = 9;
  public int JJTDELETESTATEMENT = 10;
  public int JJTDELETEVERTEXSTATEMENT = 11;
  public int JJTUPDATESTATEMENT = 12;
  public int JJTUPDATEOPERATIONS = 13;
  public int JJTUPDATEITEM = 14;
  public int JJTUPDATEINCREMENTITEM = 15;
  public int JJTUPDATEREMOVEITEM = 16;
  public int JJTUPDATEPUTITEM = 17;
  public int JJTUPDATEADDITEM = 18;
  public int JJTINSERTSTATEMENT = 19;
  public int JJTINSERTBODY = 20;
  public int JJTCREATEVERTEXSTATEMENTEMPTYNOTARGET = 21;
  public int JJTCREATEVERTEXSTATEMENTEMPTY = 22;
  public int JJTCREATEVERTEXSTATEMENT = 23;
  public int JJTCREATEVERTEXSTATEMENTNOTARGET = 24;
  public int JJTCREATEEDGESTATEMENT = 25;
  public int JJTINPUTPARAMETER = 26;
  public int JJTPOSITIONALPARAMETER = 27;
  public int JJTNAMEDPARAMETER = 28;
  public int JJTPROJECTION = 29;
  public int JJTPROJECTIONITEM = 30;
  public int JJTVALUEITEM = 31;
  public int JJTARRAYSELECTOR = 32;
  public int JJTARRAYNUMBERSELECTOR = 33;
  public int JJTARRAYSINGLEVALUESSELECTOR = 34;
  public int JJTARRAYRANGESELECTOR = 35;
  public int JJTALIAS = 36;
  public int JJTRECORDATTRIBUTE = 37;
  public int JJTTHISOPERATION = 38;
  public int JJTFUNCTIONCALL = 39;
  public int JJTMETHODCALL = 40;
  public int JJTLEVELZEROIDENTIFIER = 41;
  public int JJTSUFFIXIDENTIFIER = 42;
  public int JJTBASEIDENTIFIER = 43;
  public int JJTMODIFIER = 44;
  public int JJTEXPRESSION = 45;
  public int JJTMATHEXPRESSION = 46;
  public int JJTMULTEXPRESSION = 47;
  public int JJTFIRSTLEVELEXPRESSION = 48;
  public int JJTPARENTHESISEXPRESSION = 49;
  public int JJTBASEEXPRESSION = 50;
  public int JJTFROMCLAUSE = 51;
  public int JJTLETCLAUSE = 52;
  public int JJTLETITEM = 53;
  public int JJTFROMITEM = 54;
  public int JJTCLUSTER = 55;
  public int JJTMETADATAIDENTIFIER = 56;
  public int JJTINDEXIDENTIFIER = 57;
  public int JJTWHERECLAUSE = 58;
  public int JJTORBLOCK = 59;
  public int JJTANDBLOCK = 60;
  public int JJTNOTBLOCK = 61;
  public int JJTPARENTHESISBLOCK = 62;
  public int JJTCONDITIONBLOCK = 63;
  public int JJTCOMPAREOPERATOR = 64;
  public int JJTLTOPERATOR = 65;
  public int JJTGTOPERATOR = 66;
  public int JJTNEOPERATOR = 67;
  public int JJTNEQOPERATOR = 68;
  public int JJTGEOPERATOR = 69;
  public int JJTLEOPERATOR = 70;
  public int JJTLIKEOPERATOR = 71;
  public int JJTCONTAINSKEYOPERATOR = 72;
  public int JJTCONTAINSVALUEOPERATOR = 73;
  public int JJTEQUALSCOMPAREOPERATOR = 74;
  public int JJTBINARYCONDITION = 75;
  public int JJTCONTAINSVALUECONDITION = 76;
  public int JJTINSTANCEOFCONDITION = 77;
  public int JJTINDEXMATCHCONDITION = 78;
  public int JJTBETWEENCONDITION = 79;
  public int JJTISNULLCONDITION = 80;
  public int JJTISNOTNULLCONDITION = 81;
  public int JJTISDEFINEDCONDITION = 82;
  public int JJTISNOTDEFINEDCONDITION = 83;
  public int JJTCONTAINSCONDITION = 84;
  public int JJTINOPERATOR = 85;
  public int JJTINCONDITION = 86;
  public int JJTNOTINCONDITION = 87;
  public int JJTCONTAINSALLCONDITION = 88;
  public int JJTCONTAINSTEXTCONDITION = 89;
  public int JJTMATCHESCONDITION = 90;
  public int JJTORDERBY = 91;
  public int JJTGROUPBY = 92;
  public int JJTLIMIT = 93;
  public int JJTSKIP = 94;
  public int JJTTIMEOUT = 95;
  public int JJTWAIT = 96;
  public int JJTRETRY = 97;
  public int JJTCOLLECTION = 98;
  public int JJTFETCHPLAN = 99;
  public int JJTFETCHPLANITEM = 100;
  public int JJTTRAVERSEPROJECTIONITEM = 101;
  public int JJTARRAY = 102;
  public int JJTJSON = 103;


  public String[] jjtNodeName = {
    "Rid",
    "parse",
    "Identifier",
    "Integer",
    "FloatingPoint",
    "Number",
    "Statement",
    "SelectWithoutTargetStatement",
    "SelectStatement",
    "TraverseStatement",
    "DeleteStatement",
    "DeleteVertexStatement",
    "UpdateStatement",
    "UpdateOperations",
    "UpdateItem",
    "UpdateIncrementItem",
    "UpdateRemoveItem",
    "UpdatePutItem",
    "UpdateAddItem",
    "InsertStatement",
    "InsertBody",
    "CreateVertexStatementEmptyNoTarget",
    "CreateVertexStatementEmpty",
    "CreateVertexStatement",
    "CreateVertexStatementNoTarget",
    "CreateEdgeStatement",
    "InputParameter",
    "PositionalParameter",
    "NamedParameter",
    "Projection",
    "ProjectionItem",
    "ValueItem",
    "ArraySelector",
    "ArrayNumberSelector",
    "ArraySingleValuesSelector",
    "ArrayRangeSelector",
    "Alias",
    "RecordAttribute",
    "ThisOperation",
    "FunctionCall",
    "MethodCall",
    "LevelZeroIdentifier",
    "SuffixIdentifier",
    "BaseIdentifier",
    "Modifier",
    "Expression",
    "MathExpression",
    "MultExpression",
    "FirstLevelExpression",
    "ParenthesisExpression",
    "BaseExpression",
    "FromClause",
    "LetClause",
    "LetItem",
    "FromItem",
    "Cluster",
    "MetadataIdentifier",
    "IndexIdentifier",
    "WhereClause",
    "OrBlock",
    "AndBlock",
    "NotBlock",
    "ParenthesisBlock",
    "ConditionBlock",
    "CompareOperator",
    "LtOperator",
    "GtOperator",
    "NeOperator",
    "NeqOperator",
    "GeOperator",
    "LeOperator",
    "LikeOperator",
    "ContainsKeyOperator",
    "ContainsValueOperator",
    "EqualsCompareOperator",
    "BinaryCondition",
    "ContainsValueCondition",
    "InstanceofCondition",
    "IndexMatchCondition",
    "BetweenCondition",
    "IsNullCondition",
    "IsNotNullCondition",
    "IsDefinedCondition",
    "IsNotDefinedCondition",
    "ContainsCondition",
    "InOperator",
    "InCondition",
    "NotInCondition",
    "ContainsAllCondition",
    "ContainsTextCondition",
    "MatchesCondition",
    "OrderBy",
    "GroupBy",
    "Limit",
    "Skip",
    "Timeout",
    "Wait",
    "Retry",
    "Collection",
    "FetchPlan",
    "FetchPlanItem",
    "TraverseProjectionItem",
    "Array",
    "Json",
  };
}
/* JavaCC - OriginalChecksum=2cbda65479e7b7d8f4f9e8d374779ae6 (do not edit this line) */
