/* Generated By:JJTree&JavaCC: Do not edit this line. OrientSqlConstants.java */
package com.orientechnologies.orient.core.sql.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OrientSqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 8;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int SELECT = 11;
  /** RegularExpression Id. */
  int TRAVERSE = 12;
  /** RegularExpression Id. */
  int MATCH = 13;
  /** RegularExpression Id. */
  int INSERT = 14;
  /** RegularExpression Id. */
  int CREATE = 15;
  /** RegularExpression Id. */
  int DELETE = 16;
  /** RegularExpression Id. */
  int VERTEX = 17;
  /** RegularExpression Id. */
  int EDGE = 18;
  /** RegularExpression Id. */
  int UPDATE = 19;
  /** RegularExpression Id. */
  int UPSERT = 20;
  /** RegularExpression Id. */
  int FROM = 21;
  /** RegularExpression Id. */
  int TO = 22;
  /** RegularExpression Id. */
  int WHERE = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int INTO = 25;
  /** RegularExpression Id. */
  int VALUE = 26;
  /** RegularExpression Id. */
  int VALUES = 27;
  /** RegularExpression Id. */
  int SET = 28;
  /** RegularExpression Id. */
  int ADD = 29;
  /** RegularExpression Id. */
  int PUT = 30;
  /** RegularExpression Id. */
  int MERGE = 31;
  /** RegularExpression Id. */
  int CONTENT = 32;
  /** RegularExpression Id. */
  int REMOVE = 33;
  /** RegularExpression Id. */
  int INCREMENT = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int NULL = 37;
  /** RegularExpression Id. */
  int DEFINED = 38;
  /** RegularExpression Id. */
  int ORDER = 39;
  /** RegularExpression Id. */
  int GROUP = 40;
  /** RegularExpression Id. */
  int BY = 41;
  /** RegularExpression Id. */
  int LIMIT = 42;
  /** RegularExpression Id. */
  int SKIP2 = 43;
  /** RegularExpression Id. */
  int BATCH = 44;
  /** RegularExpression Id. */
  int OFFSET = 45;
  /** RegularExpression Id. */
  int TIMEOUT = 46;
  /** RegularExpression Id. */
  int ASC = 47;
  /** RegularExpression Id. */
  int AS = 48;
  /** RegularExpression Id. */
  int DESC = 49;
  /** RegularExpression Id. */
  int FETCHPLAN = 50;
  /** RegularExpression Id. */
  int RETURN = 51;
  /** RegularExpression Id. */
  int BEFORE = 52;
  /** RegularExpression Id. */
  int AFTER = 53;
  /** RegularExpression Id. */
  int LOCK = 54;
  /** RegularExpression Id. */
  int RECORD = 55;
  /** RegularExpression Id. */
  int WAIT = 56;
  /** RegularExpression Id. */
  int RETRY = 57;
  /** RegularExpression Id. */
  int LET = 58;
  /** RegularExpression Id. */
  int CACHE = 59;
  /** RegularExpression Id. */
  int NOCACHE = 60;
  /** RegularExpression Id. */
  int UNSAFE = 61;
  /** RegularExpression Id. */
  int PARALLEL = 62;
  /** RegularExpression Id. */
  int STRATEGY = 63;
  /** RegularExpression Id. */
  int DEPTH_FIRST = 64;
  /** RegularExpression Id. */
  int BREADTH_FIRST = 65;
  /** RegularExpression Id. */
  int LUCENE = 66;
  /** RegularExpression Id. */
  int NEAR = 67;
  /** RegularExpression Id. */
  int WITHIN = 68;
  /** RegularExpression Id. */
  int UNWIND = 69;
  /** RegularExpression Id. */
  int MAXDEPTH = 70;
  /** RegularExpression Id. */
  int MINDEPTH = 71;
  /** RegularExpression Id. */
  int CLASS = 72;
  /** RegularExpression Id. */
  int SUPERCLASS = 73;
  /** RegularExpression Id. */
  int CLASSES = 74;
  /** RegularExpression Id. */
  int SUPERCLASSES = 75;
  /** RegularExpression Id. */
  int EXCEPTION = 76;
  /** RegularExpression Id. */
  int PROFILE = 77;
  /** RegularExpression Id. */
  int STORAGE = 78;
  /** RegularExpression Id. */
  int ON = 79;
  /** RegularExpression Id. */
  int OFF = 80;
  /** RegularExpression Id. */
  int TRUNCATE = 81;
  /** RegularExpression Id. */
  int POLYMORPHIC = 82;
  /** RegularExpression Id. */
  int FIND = 83;
  /** RegularExpression Id. */
  int REFERENCES = 84;
  /** RegularExpression Id. */
  int EXTENDS = 85;
  /** RegularExpression Id. */
  int CLUSTERS = 86;
  /** RegularExpression Id. */
  int ABSTRACT = 87;
  /** RegularExpression Id. */
  int ALTER = 88;
  /** RegularExpression Id. */
  int NAME = 89;
  /** RegularExpression Id. */
  int SHORTNAME = 90;
  /** RegularExpression Id. */
  int OVERSIZE = 91;
  /** RegularExpression Id. */
  int STRICTMODE = 92;
  /** RegularExpression Id. */
  int ADDCLUSTER = 93;
  /** RegularExpression Id. */
  int REMOVECLUSTER = 94;
  /** RegularExpression Id. */
  int CUSTOM = 95;
  /** RegularExpression Id. */
  int CLUSTERSELECTION = 96;
  /** RegularExpression Id. */
  int DESCRIPTION = 97;
  /** RegularExpression Id. */
  int ENCRYPTION = 98;
  /** RegularExpression Id. */
  int DROP = 99;
  /** RegularExpression Id. */
  int PROPERTY = 100;
  /** RegularExpression Id. */
  int FORCE = 101;
  /** RegularExpression Id. */
  int METADATA = 102;
  /** RegularExpression Id. */
  int INDEX = 103;
  /** RegularExpression Id. */
  int COLLATE = 104;
  /** RegularExpression Id. */
  int ENGINE = 105;
  /** RegularExpression Id. */
  int REBUILD = 106;
  /** RegularExpression Id. */
  int ID = 107;
  /** RegularExpression Id. */
  int DATABASE = 108;
  /** RegularExpression Id. */
  int OPTIMIZE = 109;
  /** RegularExpression Id. */
  int LINK = 110;
  /** RegularExpression Id. */
  int TYPE = 111;
  /** RegularExpression Id. */
  int INVERSE = 112;
  /** RegularExpression Id. */
  int EXPLAIN = 113;
  /** RegularExpression Id. */
  int GRANT = 114;
  /** RegularExpression Id. */
  int REVOKE = 115;
  /** RegularExpression Id. */
  int READ = 116;
  /** RegularExpression Id. */
  int EXECUTE = 117;
  /** RegularExpression Id. */
  int ALL = 118;
  /** RegularExpression Id. */
  int NONE = 119;
  /** RegularExpression Id. */
  int FUNCTION = 120;
  /** RegularExpression Id. */
  int PARAMETERS = 121;
  /** RegularExpression Id. */
  int IDEMPOTENT = 122;
  /** RegularExpression Id. */
  int LANGUAGE = 123;
  /** RegularExpression Id. */
  int BEGIN = 124;
  /** RegularExpression Id. */
  int COMMIT = 125;
  /** RegularExpression Id. */
  int ROLLBACK = 126;
  /** RegularExpression Id. */
  int IF = 127;
  /** RegularExpression Id. */
  int ISOLATION = 128;
  /** RegularExpression Id. */
  int SLEEP = 129;
  /** RegularExpression Id. */
  int CONSOLE = 130;
  /** RegularExpression Id. */
  int BLOB = 131;
  /** RegularExpression Id. */
  int SHARED = 132;
  /** RegularExpression Id. */
  int DEFAULT_ = 133;
  /** RegularExpression Id. */
  int SEQUENCE = 134;
  /** RegularExpression Id. */
  int START = 135;
  /** RegularExpression Id. */
  int OPTIONAL = 136;
  /** RegularExpression Id. */
  int COUNT = 137;
  /** RegularExpression Id. */
  int HA = 138;
  /** RegularExpression Id. */
  int STATUS = 139;
  /** RegularExpression Id. */
  int THIS = 140;
  /** RegularExpression Id. */
  int RECORD_ATTRIBUTE = 141;
  /** RegularExpression Id. */
  int RID_ATTR = 142;
  /** RegularExpression Id. */
  int CLASS_ATTR = 143;
  /** RegularExpression Id. */
  int VERSION_ATTR = 144;
  /** RegularExpression Id. */
  int SIZE_ATTR = 145;
  /** RegularExpression Id. */
  int TYPE_ATTR = 146;
  /** RegularExpression Id. */
  int RAW_ATTR = 147;
  /** RegularExpression Id. */
  int RID_ID_ATTR = 148;
  /** RegularExpression Id. */
  int RID_POS_ATTR = 149;
  /** RegularExpression Id. */
  int FIELDS_ATTR = 150;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 151;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 152;
  /** RegularExpression Id. */
  int HEX_LITERAL = 153;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 154;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 155;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 156;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 157;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 158;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 159;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 160;
  /** RegularExpression Id. */
  int STRING_LITERAL = 161;
  /** RegularExpression Id. */
  int INTEGER_RANGE = 162;
  /** RegularExpression Id. */
  int TRUE = 163;
  /** RegularExpression Id. */
  int FALSE = 164;
  /** RegularExpression Id. */
  int LPAREN = 165;
  /** RegularExpression Id. */
  int RPAREN = 166;
  /** RegularExpression Id. */
  int LBRACE = 167;
  /** RegularExpression Id. */
  int RBRACE = 168;
  /** RegularExpression Id. */
  int LBRACKET = 169;
  /** RegularExpression Id. */
  int RBRACKET = 170;
  /** RegularExpression Id. */
  int SEMICOLON = 171;
  /** RegularExpression Id. */
  int COMMA = 172;
  /** RegularExpression Id. */
  int DOT = 173;
  /** RegularExpression Id. */
  int AT = 174;
  /** RegularExpression Id. */
  int DOLLAR = 175;
  /** RegularExpression Id. */
  int BACKTICK = 176;
  /** RegularExpression Id. */
  int EQ = 177;
  /** RegularExpression Id. */
  int EQEQ = 178;
  /** RegularExpression Id. */
  int LT = 179;
  /** RegularExpression Id. */
  int GT = 180;
  /** RegularExpression Id. */
  int BANG = 181;
  /** RegularExpression Id. */
  int TILDE = 182;
  /** RegularExpression Id. */
  int HOOK = 183;
  /** RegularExpression Id. */
  int COLON = 184;
  /** RegularExpression Id. */
  int LE = 185;
  /** RegularExpression Id. */
  int GE = 186;
  /** RegularExpression Id. */
  int NE = 187;
  /** RegularExpression Id. */
  int NEQ = 188;
  /** RegularExpression Id. */
  int SC_OR = 189;
  /** RegularExpression Id. */
  int SC_AND = 190;
  /** RegularExpression Id. */
  int INCR = 191;
  /** RegularExpression Id. */
  int DECR = 192;
  /** RegularExpression Id. */
  int PLUS = 193;
  /** RegularExpression Id. */
  int MINUS = 194;
  /** RegularExpression Id. */
  int STAR = 195;
  /** RegularExpression Id. */
  int SLASH = 196;
  /** RegularExpression Id. */
  int BIT_AND = 197;
  /** RegularExpression Id. */
  int BIT_OR = 198;
  /** RegularExpression Id. */
  int XOR = 199;
  /** RegularExpression Id. */
  int REM = 200;
  /** RegularExpression Id. */
  int LSHIFT = 201;
  /** RegularExpression Id. */
  int PLUSASSIGN = 202;
  /** RegularExpression Id. */
  int MINUSASSIGN = 203;
  /** RegularExpression Id. */
  int STARASSIGN = 204;
  /** RegularExpression Id. */
  int SLASHASSIGN = 205;
  /** RegularExpression Id. */
  int ANDASSIGN = 206;
  /** RegularExpression Id. */
  int ORASSIGN = 207;
  /** RegularExpression Id. */
  int XORASSIGN = 208;
  /** RegularExpression Id. */
  int REMASSIGN = 209;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 210;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 211;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 212;
  /** RegularExpression Id. */
  int ELLIPSIS = 213;
  /** RegularExpression Id. */
  int RANGE = 214;
  /** RegularExpression Id. */
  int NOT = 215;
  /** RegularExpression Id. */
  int IN = 216;
  /** RegularExpression Id. */
  int LIKE = 217;
  /** RegularExpression Id. */
  int IS = 218;
  /** RegularExpression Id. */
  int BETWEEN = 219;
  /** RegularExpression Id. */
  int CONTAINS = 220;
  /** RegularExpression Id. */
  int CONTAINSALL = 221;
  /** RegularExpression Id. */
  int CONTAINSKEY = 222;
  /** RegularExpression Id. */
  int CONTAINSVALUE = 223;
  /** RegularExpression Id. */
  int CONTAINSTEXT = 224;
  /** RegularExpression Id. */
  int MATCHES = 225;
  /** RegularExpression Id. */
  int KEY = 226;
  /** RegularExpression Id. */
  int INSTANCEOF = 227;
  /** RegularExpression Id. */
  int CLUSTER = 228;
  /** RegularExpression Id. */
  int IDENTIFIER = 229;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 230;
  /** RegularExpression Id. */
  int INDEX_COLON = 231;
  /** RegularExpression Id. */
  int INDEXVALUES_IDENTIFIER = 232;
  /** RegularExpression Id. */
  int INDEXVALUESASC_IDENTIFIER = 233;
  /** RegularExpression Id. */
  int INDEXVALUESDESC_IDENTIFIER = 234;
  /** RegularExpression Id. */
  int CLUSTER_IDENTIFIER = 235;
  /** RegularExpression Id. */
  int CLUSTER_NUMBER_IDENTIFIER = 236;
  /** RegularExpression Id. */
  int METADATA_IDENTIFIER = 237;
  /** RegularExpression Id. */
  int LETTER = 238;
  /** RegularExpression Id. */
  int PART_LETTER = 239;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 10>",
    "<SELECT>",
    "<TRAVERSE>",
    "<MATCH>",
    "<INSERT>",
    "<CREATE>",
    "<DELETE>",
    "<VERTEX>",
    "<EDGE>",
    "<UPDATE>",
    "<UPSERT>",
    "<FROM>",
    "<TO>",
    "<WHERE>",
    "<WHILE>",
    "<INTO>",
    "<VALUE>",
    "<VALUES>",
    "<SET>",
    "<ADD>",
    "<PUT>",
    "<MERGE>",
    "<CONTENT>",
    "<REMOVE>",
    "<INCREMENT>",
    "<AND>",
    "<OR>",
    "<NULL>",
    "<DEFINED>",
    "<ORDER>",
    "<GROUP>",
    "<BY>",
    "<LIMIT>",
    "<SKIP2>",
    "<BATCH>",
    "<OFFSET>",
    "<TIMEOUT>",
    "<ASC>",
    "<AS>",
    "<DESC>",
    "<FETCHPLAN>",
    "<RETURN>",
    "<BEFORE>",
    "<AFTER>",
    "<LOCK>",
    "<RECORD>",
    "<WAIT>",
    "<RETRY>",
    "<LET>",
    "<CACHE>",
    "<NOCACHE>",
    "<UNSAFE>",
    "<PARALLEL>",
    "<STRATEGY>",
    "<DEPTH_FIRST>",
    "<BREADTH_FIRST>",
    "<LUCENE>",
    "<NEAR>",
    "<WITHIN>",
    "<UNWIND>",
    "<MAXDEPTH>",
    "<MINDEPTH>",
    "<CLASS>",
    "<SUPERCLASS>",
    "<CLASSES>",
    "<SUPERCLASSES>",
    "<EXCEPTION>",
    "<PROFILE>",
    "<STORAGE>",
    "<ON>",
    "<OFF>",
    "<TRUNCATE>",
    "<POLYMORPHIC>",
    "<FIND>",
    "<REFERENCES>",
    "<EXTENDS>",
    "<CLUSTERS>",
    "<ABSTRACT>",
    "<ALTER>",
    "<NAME>",
    "<SHORTNAME>",
    "<OVERSIZE>",
    "<STRICTMODE>",
    "<ADDCLUSTER>",
    "<REMOVECLUSTER>",
    "<CUSTOM>",
    "<CLUSTERSELECTION>",
    "<DESCRIPTION>",
    "<ENCRYPTION>",
    "<DROP>",
    "<PROPERTY>",
    "<FORCE>",
    "<METADATA>",
    "<INDEX>",
    "<COLLATE>",
    "<ENGINE>",
    "<REBUILD>",
    "<ID>",
    "<DATABASE>",
    "<OPTIMIZE>",
    "<LINK>",
    "<TYPE>",
    "<INVERSE>",
    "<EXPLAIN>",
    "<GRANT>",
    "<REVOKE>",
    "<READ>",
    "<EXECUTE>",
    "<ALL>",
    "<NONE>",
    "<FUNCTION>",
    "<PARAMETERS>",
    "<IDEMPOTENT>",
    "<LANGUAGE>",
    "<BEGIN>",
    "<COMMIT>",
    "<ROLLBACK>",
    "<IF>",
    "<ISOLATION>",
    "<SLEEP>",
    "<CONSOLE>",
    "<BLOB>",
    "<SHARED>",
    "<DEFAULT_>",
    "<SEQUENCE>",
    "<START>",
    "<OPTIONAL>",
    "<COUNT>",
    "<HA>",
    "<STATUS>",
    "<THIS>",
    "<RECORD_ATTRIBUTE>",
    "<RID_ATTR>",
    "<CLASS_ATTR>",
    "<VERSION_ATTR>",
    "<SIZE_ATTR>",
    "<TYPE_ATTR>",
    "<RAW_ATTR>",
    "<RID_ID_ATTR>",
    "<RID_POS_ATTR>",
    "<FIELDS_ATTR>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<INTEGER_RANGE>",
    "\"true\"",
    "\"false\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"$\"",
    "\"`\"",
    "\"=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"<>\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"..\"",
    "<NOT>",
    "<IN>",
    "<LIKE>",
    "<IS>",
    "<BETWEEN>",
    "<CONTAINS>",
    "<CONTAINSALL>",
    "<CONTAINSKEY>",
    "<CONTAINSVALUE>",
    "<CONTAINSTEXT>",
    "<MATCHES>",
    "<KEY>",
    "<INSTANCEOF>",
    "<CLUSTER>",
    "<IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<INDEX_COLON>",
    "<INDEXVALUES_IDENTIFIER>",
    "<INDEXVALUESASC_IDENTIFIER>",
    "<INDEXVALUESDESC_IDENTIFIER>",
    "<CLUSTER_IDENTIFIER>",
    "<CLUSTER_NUMBER_IDENTIFIER>",
    "<METADATA_IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"#\"",
    "\"__@recordmap@___\"",
    "\"round-robin\"",
    "\"-servers\"",
    "\"-db\"",
    "\"-latency\"",
    "\"-messages\"",
    "\"-all\"",
    "\"-output=text\"",
  };

}
