/* Generated By:JavaCC: Do not edit this line. OrientSqlTreeConstants.java Version 5.0 */
package com.orientechnologies.orient.core.sql.parser;

public interface OrientSqlTreeConstants
{
  public int JJTRID = 0;
  public int JJTPARSE = 1;
  public int JJTPARSESCRIPT = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTINTEGER = 4;
  public int JJTFLOATINGPOINT = 5;
  public int JJTNUMBER = 6;
  public int JJTSTATEMENT = 7;
  public int JJTSTATEMENTSEMICOLON = 8;
  public int JJTSTATEMENTINTERNAL = 9;
  public int JJTQUERYSTATEMENT = 10;
  public int JJTSELECTWITHOUTTARGETSTATEMENT = 11;
  public int JJTSELECTSTATEMENT = 12;
  public int JJTTRAVERSESTATEMENT = 13;
  public int JJTMATCHSTATEMENT = 14;
  public int JJTDELETESTATEMENT = 15;
  public int JJTDELETEVERTEXSTATEMENT = 16;
  public int JJTDELETEEDGESTATEMENT = 17;
  public int JJTDELETEEDGEBYRIDSTATEMENT = 18;
  public int JJTDELETEEDGEFROMTOSTATEMENT = 19;
  public int JJTDELETEEDGETOSTATEMENT = 20;
  public int JJTDELETEEDGEVTOSTATEMENT = 21;
  public int JJTDELETEEDGEWHERESTATEMENT = 22;
  public int JJTUPDATEEDGESTATEMENT = 23;
  public int JJTUPDATESTATEMENT = 24;
  public int JJTUPDATEOPERATIONS = 25;
  public int JJTUPDATEITEM = 26;
  public int JJTUPDATEINCREMENTITEM = 27;
  public int JJTUPDATEREMOVEITEM = 28;
  public int JJTUPDATEPUTITEM = 29;
  public int JJTUPDATEADDITEM = 30;
  public int JJTINSERTSTATEMENT = 31;
  public int JJTINSERTBODY = 32;
  public int JJTCREATEVERTEXSTATEMENTEMPTYNOTARGET = 33;
  public int JJTCREATEVERTEXSTATEMENTEMPTY = 34;
  public int JJTCREATEVERTEXSTATEMENT = 35;
  public int JJTCREATEVERTEXSTATEMENTNOTARGET = 36;
  public int JJTMOVEVERTEXSTATEMENT = 37;
  public int JJTCREATEEDGESTATEMENT = 38;
  public int JJTINPUTPARAMETER = 39;
  public int JJTPOSITIONALPARAMETER = 40;
  public int JJTNAMEDPARAMETER = 41;
  public int JJTPROJECTION = 42;
  public int JJTPROJECTIONITEM = 43;
  public int JJTARRAYSELECTOR = 44;
  public int JJTARRAYNUMBERSELECTOR = 45;
  public int JJTARRAYSINGLEVALUESSELECTOR = 46;
  public int JJTARRAYRANGESELECTOR = 47;
  public int JJTALIAS = 48;
  public int JJTRECORDATTRIBUTE = 49;
  public int JJTFUNCTIONCALL = 50;
  public int JJTMETHODCALL = 51;
  public int JJTLEVELZEROIDENTIFIER = 52;
  public int JJTSUFFIXIDENTIFIER = 53;
  public int JJTBASEIDENTIFIER = 54;
  public int JJTMODIFIER = 55;
  public int JJTEXPRESSION = 56;
  public int JJTMATHEXPRESSION = 57;
  public int JJTMULTEXPRESSION = 58;
  public int JJTFIRSTLEVELEXPRESSION = 59;
  public int JJTPARENTHESISEXPRESSION = 60;
  public int JJTBASEEXPRESSION = 61;
  public int JJTFROMCLAUSE = 62;
  public int JJTLETCLAUSE = 63;
  public int JJTLETITEM = 64;
  public int JJTFROMITEM = 65;
  public int JJTCLUSTER = 66;
  public int JJTCLUSTERLIST = 67;
  public int JJTMETADATAIDENTIFIER = 68;
  public int JJTINDEXNAME = 69;
  public int JJTINDEXIDENTIFIER = 70;
  public int JJTWHERECLAUSE = 71;
  public int JJTORBLOCK = 72;
  public int JJTANDBLOCK = 73;
  public int JJTNOTBLOCK = 74;
  public int JJTPARENTHESISBLOCK = 75;
  public int JJTCONDITIONBLOCK = 76;
  public int JJTCOMPAREOPERATOR = 77;
  public int JJTLTOPERATOR = 78;
  public int JJTGTOPERATOR = 79;
  public int JJTNEOPERATOR = 80;
  public int JJTNEQOPERATOR = 81;
  public int JJTGEOPERATOR = 82;
  public int JJTLEOPERATOR = 83;
  public int JJTLIKEOPERATOR = 84;
  public int JJTLUCENEOPERATOR = 85;
  public int JJTNEAROPERATOR = 86;
  public int JJTWITHINOPERATOR = 87;
  public int JJTSCANDOPERATOR = 88;
  public int JJTCONTAINSKEYOPERATOR = 89;
  public int JJTCONTAINSVALUEOPERATOR = 90;
  public int JJTEQUALSCOMPAREOPERATOR = 91;
  public int JJTBINARYCONDITION = 92;
  public int JJTCONTAINSVALUECONDITION = 93;
  public int JJTINSTANCEOFCONDITION = 94;
  public int JJTINDEXMATCHCONDITION = 95;
  public int JJTBETWEENCONDITION = 96;
  public int JJTISNULLCONDITION = 97;
  public int JJTISNOTNULLCONDITION = 98;
  public int JJTISDEFINEDCONDITION = 99;
  public int JJTISNOTDEFINEDCONDITION = 100;
  public int JJTCONTAINSCONDITION = 101;
  public int JJTINOPERATOR = 102;
  public int JJTINCONDITION = 103;
  public int JJTNOTINCONDITION = 104;
  public int JJTCONTAINSALLCONDITION = 105;
  public int JJTCONTAINSTEXTCONDITION = 106;
  public int JJTMATCHESCONDITION = 107;
  public int JJTORDERBY = 108;
  public int JJTGROUPBY = 109;
  public int JJTUNWIND = 110;
  public int JJTLIMIT = 111;
  public int JJTSKIP = 112;
  public int JJTBATCH = 113;
  public int JJTTIMEOUT = 114;
  public int JJTWAIT = 115;
  public int JJTRETRY = 116;
  public int JJTCOLLECTION = 117;
  public int JJTFETCHPLAN = 118;
  public int JJTFETCHPLANITEM = 119;
  public int JJTTRAVERSEPROJECTIONITEM = 120;
  public int JJTJSON = 121;
  public int JJTMATCHEXPRESSION = 122;
  public int JJTMATCHPATHITEM = 123;
  public int JJTMATCHPATHITEMFIRST = 124;
  public int JJTMULTIMATCHPATHITEM = 125;
  public int JJTMULTIMATCHPATHITEMARROWS = 126;
  public int JJTMATCHFILTER = 127;
  public int JJTMATCHFILTERITEM = 128;
  public int JJTOUTPATHITEM = 129;
  public int JJTINPATHITEM = 130;
  public int JJTBOTHPATHITEM = 131;
  public int JJTOUTPATHITEMOPT = 132;
  public int JJTINPATHITEMOPT = 133;
  public int JJTBOTHPATHITEMOPT = 134;
  public int JJTPROFILESTORAGESTATEMENT = 135;
  public int JJTTRUNCATECLASSSTATEMENT = 136;
  public int JJTTRUNCATECLUSTERSTATEMENT = 137;
  public int JJTTRUNCATERECORDSTATEMENT = 138;
  public int JJTFINDREFERENCESSTATEMENT = 139;
  public int JJTCREATECLASSSTATEMENT = 140;
  public int JJTALTERCLASSSTATEMENT = 141;
  public int JJTDROPCLASSSTATEMENT = 142;
  public int JJTIFNOTEXISTS = 143;
  public int JJTCREATEPROPERTYSTATEMENT = 144;
  public int JJTCREATEPROPERTYATTRIBUTESTATEMENT = 145;
  public int JJTALTERPROPERTYSTATEMENT = 146;
  public int JJTDROPPROPERTYSTATEMENT = 147;
  public int JJTCREATEINDEXSTATEMENT = 148;
  public int JJTREBUILDINDEXSTATEMENT = 149;
  public int JJTDROPINDEXSTATEMENT = 150;
  public int JJTCREATECLUSTERSTATEMENT = 151;
  public int JJTALTERCLUSTERSTATEMENT = 152;
  public int JJTDROPCLUSTERSTATEMENT = 153;
  public int JJTALTERDATABASESTATEMENT = 154;
  public int JJTCOMMANDLINEOPTION = 155;
  public int JJTOPTIMIZEDATABASESTATEMENT = 156;
  public int JJTCREATELINKSTATEMENT = 157;
  public int JJTEXPLAINSTATEMENT = 158;
  public int JJTPERMISSION = 159;
  public int JJTRESOURCEPATHITEM = 160;
  public int JJTGRANTSTATEMENT = 161;
  public int JJTREVOKESTATEMENT = 162;
  public int JJTCREATEFUNCTIONSTATEMENT = 163;
  public int JJTLETSTATEMENT = 164;
  public int JJTBEGINSTATEMENT = 165;
  public int JJTCOMMITSTATEMENT = 166;
  public int JJTROLLBACKSTATEMENT = 167;
  public int JJTRETURNSTATEMENT = 168;
  public int JJTIFSTATEMENT = 169;
  public int JJTSLEEPSTATEMENT = 170;
  public int JJTCONSOLESTATEMENT = 171;
  public int JJTCREATESEQUENCESTATEMENT = 172;
  public int JJTALTERSEQUENCESTATEMENT = 173;
  public int JJTDROPSEQUENCESTATEMENT = 174;
  public int JJTHASTATUSSTATEMENT = 175;
  public int JJTHAREMOVESERVERSTATEMENT = 176;
  public int JJTHASYNCDATABASESTATEMENT = 177;
  public int JJTHASYNCCLUSTERSTATEMENT = 178;
  public int JJTFOREACHBLOCK = 179;


  public String[] jjtNodeName = {
    "Rid",
    "parse",
    "parseScript",
    "Identifier",
    "Integer",
    "FloatingPoint",
    "Number",
    "Statement",
    "StatementSemicolon",
    "StatementInternal",
    "QueryStatement",
    "SelectWithoutTargetStatement",
    "SelectStatement",
    "TraverseStatement",
    "MatchStatement",
    "DeleteStatement",
    "DeleteVertexStatement",
    "DeleteEdgeStatement",
    "DeleteEdgeByRidStatement",
    "DeleteEdgeFromToStatement",
    "DeleteEdgeToStatement",
    "DeleteEdgeVToStatement",
    "DeleteEdgeWhereStatement",
    "UpdateEdgeStatement",
    "UpdateStatement",
    "UpdateOperations",
    "UpdateItem",
    "UpdateIncrementItem",
    "UpdateRemoveItem",
    "UpdatePutItem",
    "UpdateAddItem",
    "InsertStatement",
    "InsertBody",
    "CreateVertexStatementEmptyNoTarget",
    "CreateVertexStatementEmpty",
    "CreateVertexStatement",
    "CreateVertexStatementNoTarget",
    "MoveVertexStatement",
    "CreateEdgeStatement",
    "InputParameter",
    "PositionalParameter",
    "NamedParameter",
    "Projection",
    "ProjectionItem",
    "ArraySelector",
    "ArrayNumberSelector",
    "ArraySingleValuesSelector",
    "ArrayRangeSelector",
    "Alias",
    "RecordAttribute",
    "FunctionCall",
    "MethodCall",
    "LevelZeroIdentifier",
    "SuffixIdentifier",
    "BaseIdentifier",
    "Modifier",
    "Expression",
    "MathExpression",
    "MultExpression",
    "FirstLevelExpression",
    "ParenthesisExpression",
    "BaseExpression",
    "FromClause",
    "LetClause",
    "LetItem",
    "FromItem",
    "Cluster",
    "ClusterList",
    "MetadataIdentifier",
    "IndexName",
    "IndexIdentifier",
    "WhereClause",
    "OrBlock",
    "AndBlock",
    "NotBlock",
    "ParenthesisBlock",
    "ConditionBlock",
    "CompareOperator",
    "LtOperator",
    "GtOperator",
    "NeOperator",
    "NeqOperator",
    "GeOperator",
    "LeOperator",
    "LikeOperator",
    "LuceneOperator",
    "NearOperator",
    "WithinOperator",
    "ScAndOperator",
    "ContainsKeyOperator",
    "ContainsValueOperator",
    "EqualsCompareOperator",
    "BinaryCondition",
    "ContainsValueCondition",
    "InstanceofCondition",
    "IndexMatchCondition",
    "BetweenCondition",
    "IsNullCondition",
    "IsNotNullCondition",
    "IsDefinedCondition",
    "IsNotDefinedCondition",
    "ContainsCondition",
    "InOperator",
    "InCondition",
    "NotInCondition",
    "ContainsAllCondition",
    "ContainsTextCondition",
    "MatchesCondition",
    "OrderBy",
    "GroupBy",
    "Unwind",
    "Limit",
    "Skip",
    "Batch",
    "Timeout",
    "Wait",
    "Retry",
    "Collection",
    "FetchPlan",
    "FetchPlanItem",
    "TraverseProjectionItem",
    "Json",
    "MatchExpression",
    "MatchPathItem",
    "MatchPathItemFirst",
    "MultiMatchPathItem",
    "MultiMatchPathItemArrows",
    "MatchFilter",
    "MatchFilterItem",
    "OutPathItem",
    "InPathItem",
    "BothPathItem",
    "OutPathItemOpt",
    "InPathItemOpt",
    "BothPathItemOpt",
    "ProfileStorageStatement",
    "TruncateClassStatement",
    "TruncateClusterStatement",
    "TruncateRecordStatement",
    "FindReferencesStatement",
    "CreateClassStatement",
    "AlterClassStatement",
    "DropClassStatement",
    "IfNotExists",
    "CreatePropertyStatement",
    "CreatePropertyAttributeStatement",
    "AlterPropertyStatement",
    "DropPropertyStatement",
    "CreateIndexStatement",
    "RebuildIndexStatement",
    "DropIndexStatement",
    "CreateClusterStatement",
    "AlterClusterStatement",
    "DropClusterStatement",
    "AlterDatabaseStatement",
    "CommandLineOption",
    "OptimizeDatabaseStatement",
    "CreateLinkStatement",
    "ExplainStatement",
    "Permission",
    "ResourcePathItem",
    "GrantStatement",
    "RevokeStatement",
    "CreateFunctionStatement",
    "LetStatement",
    "BeginStatement",
    "CommitStatement",
    "RollbackStatement",
    "ReturnStatement",
    "IfStatement",
    "SleepStatement",
    "ConsoleStatement",
    "CreateSequenceStatement",
    "AlterSequenceStatement",
    "DropSequenceStatement",
    "HaStatusStatement",
    "HaRemoveServerStatement",
    "HaSyncDatabaseStatement",
    "HaSyncClusterStatement",
    "ForEachBlock",
  };
}
/* JavaCC - OriginalChecksum=877cfff7515fb5df29eba7c38ea8f217 (do not edit this line) */
