/* Generated By:JJTree&JavaCC: Do not edit this line. OrientSqlTokenManager.java */
package com.orientechnologies.orient.core.sql.parser;

/** Token Manager. */
public class OrientSqlTokenManager implements OrientSqlConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1000000000000000L) != 0L || (active1 & 0x600000000L) != 0L)
            return 36;
         if ((active1 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 112;
            return 154;
         }
         if ((active0 & 0x2000000100000000L) != 0L)
            return 32;
         if ((active1 & 0x805000L) != 0L)
            return 51;
         return -1;
      case 1:
         if ((active1 & 0x800000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 100;
               jjmatchedPos = 1;
            }
            return 155;
         }
         if ((active0 & 0x100000000L) != 0L)
            return 137;
         return -1;
      case 2:
         if ((active1 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 2;
            return 156;
         }
         return -1;
      case 3:
         if ((active1 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 3;
            return 79;
         }
         return -1;
      case 4:
         if ((active1 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 4;
            return 79;
         }
         return -1;
      case 5:
         if ((active1 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 5;
            return 79;
         }
         return -1;
      case 6:
         if ((active1 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 6;
            return 79;
         }
         return -1;
      case 7:
         if ((active1 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 7;
            return 79;
         }
         return -1;
      case 8:
         if ((active1 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 8;
            return 79;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 65;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L);
      case 35:
         return jjStopAtPos(0, 121);
      case 37:
         jjmatchedKind = 84;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000000L);
      case 38:
         jjmatchedKind = 81;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000400L);
      case 40:
         return jjStopAtPos(0, 52);
      case 41:
         return jjStopAtPos(0, 53);
      case 42:
         jjmatchedKind = 79;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1000000L);
      case 43:
         jjmatchedKind = 77;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400800L);
      case 44:
         return jjStopAtPos(0, 59);
      case 45:
         jjmatchedKind = 78;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x801000L);
      case 46:
         jjmatchedKind = 60;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x600000000L);
      case 47:
         jjmatchedKind = 80;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000L);
      case 58:
         return jjStopAtPos(0, 68);
      case 59:
         return jjStopAtPos(0, 58);
      case 60:
         jjmatchedKind = 63;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40200120L);
      case 61:
         return jjStopAtPos(0, 62);
      case 62:
         jjmatchedKind = 64;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x180000040L);
      case 63:
         return jjStopAtPos(0, 67);
      case 64:
         jjmatchedKind = 61;
         return jjMoveStringLiteralDfa1_0(0x100000000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 56);
      case 93:
         return jjStopAtPos(0, 57);
      case 94:
         jjmatchedKind = 83;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000000000L);
      case 123:
         return jjStopAtPos(0, 54);
      case 124:
         jjmatchedKind = 82;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000200L);
      case 125:
         return jjStopAtPos(0, 55);
      case 126:
         return jjStopAtPos(0, 66);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x400L) != 0L)
            return jjStopAtPos(1, 74);
         break;
      case 43:
         if ((active1 & 0x800L) != 0L)
            return jjStopAtPos(1, 75);
         break;
      case 45:
         if ((active1 & 0x1000L) != 0L)
            return jjStopAtPos(1, 76);
         break;
      case 46:
         if ((active1 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x200000000L);
      case 60:
         if ((active1 & 0x200000L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40000000L);
      case 61:
         if ((active1 & 0x20L) != 0L)
            return jjStopAtPos(1, 69);
         else if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(1, 70);
         else if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(1, 71);
         else if ((active1 & 0x400000L) != 0L)
            return jjStopAtPos(1, 86);
         else if ((active1 & 0x800000L) != 0L)
            return jjStopAtPos(1, 87);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStopAtPos(1, 88);
         else if ((active1 & 0x2000000L) != 0L)
            return jjStopAtPos(1, 89);
         else if ((active1 & 0x4000000L) != 0L)
            return jjStopAtPos(1, 90);
         else if ((active1 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 91);
         else if ((active1 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 92);
         else if ((active1 & 0x20000000L) != 0L)
            return jjStopAtPos(1, 93);
         break;
      case 62:
         if ((active1 & 0x100L) != 0L)
            return jjStopAtPos(1, 72);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x180000000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800000000000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L, active1, 0L);
      case 124:
         if ((active1 & 0x200L) != 0L)
            return jjStopAtPos(1, 73);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 46:
         if ((active1 & 0x200000000L) != 0L)
            return jjStopAtPos(2, 97);
         break;
      case 61:
         if ((active1 & 0x40000000L) != 0L)
            return jjStopAtPos(2, 94);
         else if ((active1 & 0x80000000L) != 0L)
            return jjStopAtPos(2, 95);
         break;
      case 62:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100000000L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 61:
         if ((active1 & 0x100000000L) != 0L)
            return jjStopAtPos(3, 96);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x800000000000L);
      case 115:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(4, 32);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, 0L, active1);
      return 5;
   }
   switch(curChar)
   {
      case 110:
         return jjMoveStringLiteralDfa6_0(active1, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, 0L, active1);
}
private int jjMoveStringLiteralDfa6_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(4, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, 0L, active1);
      return 6;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa7_0(active1, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, 0L, active1);
}
private int jjMoveStringLiteralDfa7_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(5, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, 0L, active1);
      return 7;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa8_0(active1, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, 0L, active1);
}
private int jjMoveStringLiteralDfa8_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(6, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, 0L, active1);
      return 8;
   }
   switch(curChar)
   {
      case 111:
         return jjMoveStringLiteralDfa9_0(active1, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, 0L, active1);
}
private int jjMoveStringLiteralDfa9_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(7, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, 0L, active1);
      return 9;
   }
   switch(curChar)
   {
      case 102:
         if ((active1 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 111, 79);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, 0L, active1);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 394;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 156:
               case 79:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  jjCheckNAdd(79);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 6);
                  else if (curChar == 39)
                     jjCheckNAddStates(7, 11);
                  else if (curChar == 45)
                     jjAddStates(12, 13);
                  else if (curChar == 34)
                     jjCheckNAddStates(14, 16);
                  else if (curChar == 46)
                     jjCheckNAdd(36);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAddStates(17, 21);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAddStates(22, 30);
                  }
                  break;
               case 155:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  jjCheckNAdd(79);
                  break;
               case 51:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(31, 33);
                  else if (curChar == 48)
                     jjCheckNAddStates(34, 37);
                  break;
               case 154:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  jjCheckNAdd(79);
                  break;
               case 35:
                  if (curChar == 46)
                     jjCheckNAdd(36);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddStates(38, 40);
                  break;
               case 38:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(39);
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddTwoStates(39, 40);
                  break;
               case 41:
                  if (curChar == 34)
                     jjCheckNAddStates(14, 16);
                  break;
               case 42:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(14, 16);
                  break;
               case 44:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(14, 16);
                  break;
               case 45:
                  if (curChar == 34 && kind > 50)
                     kind = 50;
                  break;
               case 46:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(41, 44);
                  break;
               case 47:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(14, 16);
                  break;
               case 48:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(47);
                  break;
               case 50:
                  if (curChar == 45)
                     jjAddStates(12, 13);
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(31, 33);
                  break;
               case 54:
                  if (curChar == 46)
                     jjCheckNAddStates(45, 47);
                  break;
               case 55:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(56, 59);
                  break;
               case 56:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddTwoStates(57, 58);
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddTwoStates(57, 58);
                  break;
               case 59:
                  if (curChar != 48)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(48, 50);
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddTwoStates(61, 58);
                  break;
               case 62:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddTwoStates(62, 58);
                  break;
               case 63:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 64:
                  if (curChar == 48)
                     jjCheckNAddStates(34, 37);
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(51, 53);
                  break;
               case 67:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(54, 56);
                  break;
               case 80:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 82:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 117)
                     kind = 117;
                  jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 90:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 92:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 118)
                     kind = 118;
                  jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 104:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 6);
                  break;
               case 105:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(57, 59);
                  break;
               case 107:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(108);
                  break;
               case 108:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(108, 40);
                  break;
               case 109:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(109, 110);
                  break;
               case 111:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(112);
                  break;
               case 112:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddTwoStates(112, 40);
                  break;
               case 113:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(113, 114);
                  break;
               case 114:
                  if (curChar != 46)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddStates(60, 62);
                  break;
               case 115:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddStates(60, 62);
                  break;
               case 117:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(118);
                  break;
               case 118:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddTwoStates(118, 40);
                  break;
               case 240:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddStates(17, 21);
                  break;
               case 241:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(241, 242);
                  break;
               case 243:
                  if (curChar == 39)
                     jjCheckNAddStates(7, 11);
                  break;
               case 244:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAdd(245);
                  break;
               case 245:
                  if (curChar == 39 && kind > 49)
                     kind = 49;
                  break;
               case 247:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(245);
                  break;
               case 248:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(249, 245);
                  break;
               case 249:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(245);
                  break;
               case 250:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 251:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(249);
                  break;
               case 252:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAddStates(63, 65);
                  break;
               case 254:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(63, 65);
                  break;
               case 255:
                  if (curChar == 39 && kind > 50)
                     kind = 50;
                  break;
               case 256:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(66, 69);
                  break;
               case 257:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(63, 65);
                  break;
               case 258:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 259:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(257);
                  break;
               case 312:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 313;
                  break;
               case 314:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 113)
                     kind = 113;
                  jjCheckNAddTwoStates(314, 315);
                  break;
               case 315:
                  if ((0x600000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 316;
                  break;
               case 317:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 113)
                     kind = 113;
                  jjCheckNAddTwoStates(315, 317);
                  break;
               case 322:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 323;
                  break;
               case 324:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 114)
                     kind = 114;
                  jjCheckNAddTwoStates(324, 325);
                  break;
               case 325:
                  if ((0x600000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 326;
                  break;
               case 327:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 114)
                     kind = 114;
                  jjCheckNAddTwoStates(325, 327);
                  break;
               case 338:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 339;
                  break;
               case 340:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  jjCheckNAddTwoStates(340, 341);
                  break;
               case 341:
                  if ((0x600000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 342;
                  break;
               case 343:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  jjCheckNAddTwoStates(341, 343);
                  break;
               case 357:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 358;
                  break;
               case 359:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 116)
                     kind = 116;
                  jjCheckNAddTwoStates(359, 360);
                  break;
               case 360:
                  if ((0x600000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 361;
                  break;
               case 362:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 116)
                     kind = 116;
                  jjCheckNAddTwoStates(360, 362);
                  break;
               case 377:
                  if (curChar != 48)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddStates(22, 30);
                  break;
               case 379:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(379, 242);
                  break;
               case 380:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(380, 242);
                  break;
               case 382:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(70, 71);
                  break;
               case 383:
                  if (curChar == 46)
                     jjCheckNAdd(384);
                  break;
               case 384:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(384, 385);
                  break;
               case 386:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(387);
                  break;
               case 387:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddTwoStates(387, 40);
                  break;
               case 389:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(72, 74);
                  break;
               case 390:
                  if (curChar == 46)
                     jjCheckNAdd(391);
                  break;
               case 392:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(393);
                  break;
               case 393:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddTwoStates(393, 40);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 156:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 112)
                        kind = 112;
                     jjCheckNAdd(79);
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 112)
                        kind = 112;
                     jjCheckNAdd(79);
                  }
                  else if (curChar == 64)
                     jjAddStates(75, 79);
                  if ((0x800000008L & l) != 0L)
                     jjAddStates(80, 84);
                  else if ((0x100000001000L & l) != 0L)
                     jjAddStates(85, 86);
                  else if ((0x400000004L & l) != 0L)
                     jjAddStates(87, 88);
                  else if ((0x400000004000L & l) != 0L)
                     jjAddStates(89, 90);
                  else if ((0x800000008000L & l) != 0L)
                     jjAddStates(91, 93);
                  else if ((0x200000002L & l) != 0L)
                     jjAddStates(94, 97);
                  else if ((0x80000000800000L & l) != 0L)
                     jjAddStates(98, 99);
                  else if ((0x4000000040L & l) != 0L)
                     jjAddStates(100, 101);
                  else if ((0x1000000010L & l) != 0L)
                     jjAddStates(102, 104);
                  else if ((0x20000000200L & l) != 0L)
                     jjAddStates(105, 107);
                  else if ((0x8000000080000L & l) != 0L)
                     jjAddStates(108, 110);
                  else if ((0x80000000800L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  else if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  else if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  else if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  else if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  else if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 1;
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 32;
                  if (curChar == 105)
                     jjCheckNAddStates(111, 116);
                  else if (curChar == 73)
                     jjCheckNAddTwoStates(102, 103);
                  else if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 99;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 155:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 112)
                        kind = 112;
                     jjCheckNAdd(79);
                  }
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 161;
                  else if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 156;
                  else if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 374;
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 354;
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 335;
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 319;
                  break;
               case 154:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 112)
                        kind = 112;
                     jjCheckNAdd(79);
                  }
                  if ((0x400000004000L & l) != 0L)
                  {
                     if (kind > 100)
                        kind = 100;
                  }
                  else if (curChar == 83)
                  {
                     if (kind > 102)
                        kind = 102;
                  }
                  else if (curChar == 115)
                  {
                     if (kind > 102)
                        kind = 102;
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 160;
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 155;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 375;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 355;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 336;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 320;
                  break;
               case 32:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 137;
                  else if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 134;
                  else if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 130;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 123;
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 1:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 4:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 5:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 7:
                  if ((0x2000000020L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 8:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 11:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 12:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0x2000000020L & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 14:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 15:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 16:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 18:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  if ((0x8000000080000L & l) != 0L && kind > 14)
                     kind = 14;
                  break;
               case 20:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 21:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 22:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 24:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0x2000000020L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 26:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0x1000000010000L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 31:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 33:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x1000000010L & l) != 0L && kind > 33)
                     kind = 33;
                  break;
               case 37:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(117, 118);
                  break;
               case 40:
                  if ((0x5000000050L & l) != 0L && kind > 44)
                     kind = 44;
                  break;
               case 42:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(14, 16);
                  break;
               case 43:
                  if (curChar == 92)
                     jjAddStates(119, 121);
                  break;
               case 44:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(14, 16);
                  break;
               case 53:
                  if ((0x100000001000L & l) != 0L)
                     jjCheckNAdd(63);
                  break;
               case 58:
                  if ((0x100000001000L & l) != 0L && kind > 51)
                     kind = 51;
                  break;
               case 60:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(61);
                  break;
               case 61:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddTwoStates(61, 58);
                  break;
               case 65:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(66);
                  break;
               case 66:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(51, 53);
                  break;
               case 68:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 70:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 72:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x8000000080000L & l) != 0L && kind > 109)
                     kind = 109;
                  break;
               case 75:
                  if ((0x80000000800L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x200000002000000L & l) != 0L && kind > 110)
                     kind = 110;
                  break;
               case 78:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  jjCheckNAdd(79);
                  break;
               case 79:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  jjCheckNAdd(79);
                  break;
               case 81:
               case 82:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 117)
                     kind = 117;
                  jjCheckNAdd(82);
                  break;
               case 83:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 84:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 91:
               case 92:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 118)
                     kind = 118;
                  jjCheckNAdd(92);
                  break;
               case 93:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 94:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 95:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 73)
                     jjCheckNAddTwoStates(102, 103);
                  break;
               case 102:
                  if (curChar == 83 && kind > 102)
                     kind = 102;
                  break;
               case 103:
                  if (curChar == 115 && kind > 102)
                     kind = 102;
                  break;
               case 106:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(122, 123);
                  break;
               case 110:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(124, 125);
                  break;
               case 116:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(126, 127);
                  break;
               case 119:
                  if (curChar == 64)
                     jjAddStates(75, 79);
                  break;
               case 120:
                  if (curChar == 115 && kind > 33)
                     kind = 33;
                  break;
               case 121:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 110 && kind > 33)
                     kind = 33;
                  break;
               case 126:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 101 && kind > 33)
                     kind = 33;
                  break;
               case 133:
                  if (curChar == 122)
                     jjCheckNAdd(132);
                  break;
               case 134:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 112)
                     jjCheckNAdd(132);
                  break;
               case 137:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 119 && kind > 33)
                     kind = 33;
                  break;
               case 140:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(108, 110);
                  break;
               case 143:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 144:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 145:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 146:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 147:
                  if ((0x10000000100000L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 148:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 149:
                  if ((0x10000000100000L & l) != 0L && kind > 15)
                     kind = 15;
                  break;
               case 150:
                  if ((0x80000000800L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 151:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 152:
                  if ((0x1000000010000L & l) != 0L && kind > 26)
                     kind = 26;
                  break;
               case 153:
                  if ((0x20000000200L & l) != 0L)
                     jjAddStates(105, 107);
                  break;
               case 157:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 158:
                  if ((0x10000000100000L & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 159:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 160:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 161:
                  if ((0x800000008000L & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               case 162:
                  if ((0x400000004000L & l) != 0L && kind > 100)
                     kind = 100;
                  break;
               case 163:
                  if ((0x1000000010L & l) != 0L)
                     jjAddStates(102, 104);
                  break;
               case 164:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 165:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 166:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 167:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 168:
                  if ((0x2000000020L & l) != 0L && kind > 9)
                     kind = 9;
                  break;
               case 169:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 170:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 171:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 172:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 173:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 174:
                  if ((0x1000000010L & l) != 0L && kind > 21)
                     kind = 21;
                  break;
               case 175:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 176:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 177:
                  if ((0x800000008L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 178:
                  if ((0x4000000040L & l) != 0L)
                     jjAddStates(100, 101);
                  break;
               case 179:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 180:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 181:
                  if ((0x200000002000L & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 182:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 183:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 184:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 185:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 186:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 187:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 188:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 189:
                  if ((0x400000004000L & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 190:
                  if ((0x80000000800000L & l) != 0L)
                     jjAddStates(98, 99);
                  break;
               case 191:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 192:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 193:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 194:
                  if ((0x2000000020L & l) != 0L && kind > 11)
                     kind = 11;
                  break;
               case 195:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 196:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 197:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 198:
                  if ((0x2000000020L & l) != 0L && kind > 12)
                     kind = 12;
                  break;
               case 199:
                  if ((0x200000002L & l) != 0L)
                     jjAddStates(94, 97);
                  break;
               case 200:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 201:
                  if ((0x1000000010L & l) != 0L && kind > 16)
                     kind = 16;
                  break;
               case 202:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 203:
                  if ((0x1000000010L & l) != 0L && kind > 18)
                     kind = 18;
                  break;
               case 204:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 205:
                  if ((0x800000008L & l) != 0L && kind > 28)
                     kind = 28;
                  break;
               case 206:
                  if ((0x8000000080000L & l) != 0L && kind > 29)
                     kind = 29;
                  break;
               case 207:
                  if ((0x800000008000L & l) != 0L)
                     jjAddStates(91, 93);
                  break;
               case 208:
                  if ((0x4000000040000L & l) != 0L && kind > 19)
                     kind = 19;
                  break;
               case 209:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 210:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 211:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 212;
                  break;
               case 212:
                  if ((0x4000000040000L & l) != 0L && kind > 22)
                     kind = 22;
                  break;
               case 213:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 214:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 215:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 216:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 217:
                  if ((0x10000000100000L & l) != 0L && kind > 27)
                     kind = 27;
                  break;
               case 218:
                  if ((0x400000004000L & l) != 0L)
                     jjAddStates(89, 90);
                  break;
               case 219:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 220:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 221:
                  if ((0x100000001000L & l) != 0L && kind > 20)
                     kind = 20;
                  break;
               case 222:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 223:
                  if ((0x10000000100000L & l) != 0L && kind > 99)
                     kind = 99;
                  break;
               case 224:
                  if ((0x400000004L & l) != 0L)
                     jjAddStates(87, 88);
                  break;
               case 225:
                  if ((0x200000002000000L & l) != 0L && kind > 24)
                     kind = 24;
                  break;
               case 226:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 227:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 228:
                  if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 229:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 230:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 231:
                  if ((0x400000004000L & l) != 0L && kind > 103)
                     kind = 103;
                  break;
               case 232:
                  if ((0x100000001000L & l) != 0L)
                     jjAddStates(85, 86);
                  break;
               case 233:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 234:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 235:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 236:
                  if ((0x10000000100000L & l) != 0L && kind > 25)
                     kind = 25;
                  break;
               case 237:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 238:
                  if ((0x80000000800L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 239:
                  if ((0x2000000020L & l) != 0L && kind > 101)
                     kind = 101;
                  break;
               case 242:
                  if ((0x100000001000L & l) != 0L && kind > 40)
                     kind = 40;
                  break;
               case 244:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(245);
                  break;
               case 246:
                  if (curChar == 92)
                     jjAddStates(128, 130);
                  break;
               case 247:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAdd(245);
                  break;
               case 252:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(63, 65);
                  break;
               case 253:
                  if (curChar == 92)
                     jjAddStates(131, 133);
                  break;
               case 254:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(63, 65);
                  break;
               case 260:
                  if ((0x800000008L & l) != 0L)
                     jjAddStates(80, 84);
                  break;
               case 261:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 262:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 263:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 264;
                  break;
               case 264:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 265:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 266:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 267:
                  if ((0x8000000080000L & l) != 0L && kind > 104)
                     kind = 104;
                  break;
               case 268:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 269:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 270:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 271:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 272:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 273:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 274:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 275:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 276:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 277:
                  if ((0x100000001000L & l) != 0L && kind > 105)
                     kind = 105;
                  break;
               case 278:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 279:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 280:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 281:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 282:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 283:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 284:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 285:
                  if ((0x80000000800L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 286:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 287;
                  break;
               case 287:
                  if ((0x200000002000000L & l) != 0L && kind > 106)
                     kind = 106;
                  break;
               case 288:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 289;
                  break;
               case 289:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 290:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 291;
                  break;
               case 291:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 292:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 293;
                  break;
               case 293:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 294;
                  break;
               case 294:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 295;
                  break;
               case 295:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 296:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 297;
                  break;
               case 297:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 298;
                  break;
               case 298:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 299;
                  break;
               case 299:
                  if ((0x2000000020L & l) != 0L && kind > 107)
                     kind = 107;
                  break;
               case 300:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 301;
                  break;
               case 301:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 302;
                  break;
               case 302:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 303:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 304:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 305;
                  break;
               case 305:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 306;
                  break;
               case 306:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 307;
                  break;
               case 307:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 308;
                  break;
               case 308:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 309;
                  break;
               case 309:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 310;
                  break;
               case 310:
                  if ((0x10000000100000L & l) != 0L && kind > 108)
                     kind = 108;
                  break;
               case 311:
                  if (curChar == 105)
                     jjCheckNAddStates(111, 116);
                  break;
               case 313:
               case 314:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 113)
                     kind = 113;
                  jjCheckNAddTwoStates(314, 315);
                  break;
               case 316:
               case 317:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 113)
                     kind = 113;
                  jjCheckNAddTwoStates(315, 317);
                  break;
               case 318:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 312;
                  break;
               case 319:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 318;
                  break;
               case 320:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 319;
                  break;
               case 321:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 320;
                  break;
               case 323:
               case 324:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 114)
                     kind = 114;
                  jjCheckNAddTwoStates(324, 325);
                  break;
               case 326:
               case 327:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 114)
                     kind = 114;
                  jjCheckNAddTwoStates(325, 327);
                  break;
               case 328:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 322;
                  break;
               case 329:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 328;
                  break;
               case 330:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 329;
                  break;
               case 331:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 330;
                  break;
               case 332:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 331;
                  break;
               case 333:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 332;
                  break;
               case 334:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 333;
                  break;
               case 335:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 334;
                  break;
               case 336:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 335;
                  break;
               case 337:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 336;
                  break;
               case 339:
               case 340:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  jjCheckNAddTwoStates(340, 341);
                  break;
               case 342:
               case 343:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  jjCheckNAddTwoStates(341, 343);
                  break;
               case 344:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 338;
                  break;
               case 345:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 344;
                  break;
               case 346:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 345;
                  break;
               case 347:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 346;
                  break;
               case 348:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 347;
                  break;
               case 349:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 348;
                  break;
               case 350:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 349;
                  break;
               case 351:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 350;
                  break;
               case 352:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 351;
                  break;
               case 353:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 352;
                  break;
               case 354:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 353;
                  break;
               case 355:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 354;
                  break;
               case 356:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 355;
                  break;
               case 358:
               case 359:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 116)
                     kind = 116;
                  jjCheckNAddTwoStates(359, 360);
                  break;
               case 361:
               case 362:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 116)
                     kind = 116;
                  jjCheckNAddTwoStates(360, 362);
                  break;
               case 363:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 357;
                  break;
               case 364:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 363;
                  break;
               case 365:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 364;
                  break;
               case 366:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 365;
                  break;
               case 367:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 366;
                  break;
               case 368:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 367;
                  break;
               case 369:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 368;
                  break;
               case 370:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 369;
                  break;
               case 371:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 370;
                  break;
               case 372:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 371;
                  break;
               case 373:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 372;
                  break;
               case 374:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 373;
                  break;
               case 375:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 374;
                  break;
               case 376:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 375;
                  break;
               case 378:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(379);
                  break;
               case 379:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAddTwoStates(379, 242);
                  break;
               case 381:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAddTwoStates(382, 383);
                  break;
               case 382:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(382, 383);
                  break;
               case 384:
                  if ((0x7e0000007eL & l) != 0L)
                     jjAddStates(134, 135);
                  break;
               case 385:
                  if ((0x1000000010000L & l) != 0L)
                     jjAddStates(136, 137);
                  break;
               case 388:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(389);
                  break;
               case 389:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(72, 74);
                  break;
               case 391:
                  if ((0x1000000010000L & l) != 0L)
                     jjAddStates(138, 139);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 42:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(14, 16);
                  break;
               case 244:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 252:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(63, 65);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 394 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   105, 106, 40, 109, 110, 113, 114, 244, 246, 252, 253, 255, 51, 64, 42, 43, 
   45, 241, 242, 52, 53, 63, 378, 380, 242, 381, 388, 65, 67, 53, 63, 52, 
   53, 63, 65, 67, 53, 63, 36, 37, 40, 42, 43, 47, 45, 55, 56, 59, 
   60, 62, 58, 66, 53, 63, 67, 53, 63, 105, 106, 40, 115, 116, 40, 252, 
   253, 255, 252, 253, 257, 255, 382, 383, 389, 390, 391, 124, 131, 135, 138, 141, 
   261, 268, 278, 288, 300, 233, 237, 225, 226, 219, 222, 208, 209, 213, 200, 202, 
   204, 206, 191, 195, 179, 182, 164, 169, 175, 154, 159, 162, 143, 148, 150, 103, 
   102, 321, 337, 356, 376, 38, 39, 44, 46, 48, 107, 108, 111, 112, 117, 118, 
   247, 248, 250, 254, 256, 258, 384, 385, 386, 387, 392, 393, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, "\100\164\150\151\163", null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
"\50", "\51", "\173", "\175", "\133", "\135", "\73", "\54", "\56", "\100", "\75", 
"\74", "\76", "\41", "\176", "\77", "\72", "\74\75", "\76\75", "\41\75", "\74\76", 
"\174\174", "\46\46", "\53\53", "\55\55", "\53", "\55", "\52", "\57", "\46", "\174", 
"\136", "\45", "\74\74", "\53\75", "\55\75", "\52\75", "\57\75", "\46\75", "\174\75", 
"\136\75", "\45\75", "\74\74\75", "\76\76\75", "\76\76\76\75", "\56\56\56", "\56\56", 
null, null, null, null, null, null, null, null, null, null, null, null, 
"\151\156\163\164\141\156\143\145\157\146", null, null, null, null, null, null, null, null, null, "\43", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xfffe1103ffffffe1L, 0x27fffffffffffffL, 
};
static final long[] jjtoSkip = {
   0x1eL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[394];
private final int[] jjstateSet = new int[788];
protected char curChar;
/** Constructor. */
public OrientSqlTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public OrientSqlTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 394; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
