/* Generated By:JavaCC: Do not edit this line. OrientSqlTreeConstants.java Version 5.0 */
package com.orientechnologies.orient.core.sql.parser;

public interface OrientSqlTreeConstants
{
  public int JJTRID = 0;
  public int JJTPARSE = 1;
  public int JJTPARSESCRIPT = 2;
  public int JJTSTRING = 3;
  public int JJTIDENTIFIER = 4;
  public int JJTINTEGER = 5;
  public int JJTFLOATINGPOINT = 6;
  public int JJTNUMBER = 7;
  public int JJTSTATEMENT = 8;
  public int JJTSTATEMENTSEMICOLON = 9;
  public int JJTSTATEMENTINTERNAL = 10;
  public int JJTEXPRESSIONSTATEMENT = 11;
  public int JJTQUERYSTATEMENT = 12;
  public int JJTSELECTWITHOUTTARGETSTATEMENT = 13;
  public int JJTSELECTSTATEMENT = 14;
  public int JJTTRAVERSESTATEMENT = 15;
  public int JJTMATCHSTATEMENT = 16;
  public int JJTDELETESTATEMENT = 17;
  public int JJTDELETEVERTEXSTATEMENT = 18;
  public int JJTDELETEEDGESTATEMENT = 19;
  public int JJTDELETEEDGEBYRIDSTATEMENT = 20;
  public int JJTDELETEEDGEFROMTOSTATEMENT = 21;
  public int JJTDELETEEDGETOSTATEMENT = 22;
  public int JJTDELETEEDGEVTOSTATEMENT = 23;
  public int JJTDELETEEDGEWHERESTATEMENT = 24;
  public int JJTUPDATEEDGESTATEMENT = 25;
  public int JJTUPDATESTATEMENT = 26;
  public int JJTUPDATEOPERATIONS = 27;
  public int JJTUPDATEITEM = 28;
  public int JJTUPDATEINCREMENTITEM = 29;
  public int JJTUPDATEREMOVEITEM = 30;
  public int JJTUPDATEPUTITEM = 31;
  public int JJTINSERTSTATEMENT = 32;
  public int JJTINSERTBODY = 33;
  public int JJTCREATEVERTEXSTATEMENTEMPTYNOTARGET = 34;
  public int JJTCREATEVERTEXSTATEMENT = 35;
  public int JJTCREATEVERTEXSTATEMENTNOTARGET = 36;
  public int JJTMOVEVERTEXSTATEMENT = 37;
  public int JJTCREATEEDGESTATEMENT = 38;
  public int JJTINPUTPARAMETER = 39;
  public int JJTPOSITIONALPARAMETER = 40;
  public int JJTNAMEDPARAMETER = 41;
  public int JJTPROJECTION = 42;
  public int JJTPROJECTIONITEM = 43;
  public int JJTNESTEDPROJECTION = 44;
  public int JJTNESTEDPROJECTIONITEM = 45;
  public int JJTARRAYSELECTOR = 46;
  public int JJTARRAYNUMBERSELECTOR = 47;
  public int JJTARRAYSINGLEVALUESSELECTOR = 48;
  public int JJTARRAYRANGESELECTOR = 49;
  public int JJTALIAS = 50;
  public int JJTRECORDATTRIBUTE = 51;
  public int JJTFUNCTIONCALL = 52;
  public int JJTMETHODCALL = 53;
  public int JJTLEVELZEROIDENTIFIER = 54;
  public int JJTSUFFIXIDENTIFIER = 55;
  public int JJTBASEIDENTIFIER = 56;
  public int JJTMODIFIER = 57;
  public int JJTEXPRESSION = 58;
  public int JJTARRAYCONCATEXPRESSION = 59;
  public int JJTARRAYCONCATEXPRESSIONELEMENT = 60;
  public int JJTMATHEXPRESSION = 61;
  public int JJTFIRSTLEVELEXPRESSION = 62;
  public int JJTPARENTHESISEXPRESSION = 63;
  public int JJTBASEEXPRESSION = 64;
  public int JJTFROMCLAUSE = 65;
  public int JJTLETCLAUSE = 66;
  public int JJTLETITEM = 67;
  public int JJTFROMITEM = 68;
  public int JJTCLUSTER = 69;
  public int JJTCLUSTERLIST = 70;
  public int JJTMETADATAIDENTIFIER = 71;
  public int JJTINDEXNAME = 72;
  public int JJTINDEXIDENTIFIER = 73;
  public int JJTWHERECLAUSE = 74;
  public int JJTORBLOCK = 75;
  public int JJTANDBLOCK = 76;
  public int JJTNOTBLOCK = 77;
  public int JJTPARENTHESISBLOCK = 78;
  public int JJTCONDITIONBLOCK = 79;
  public int JJTCOMPAREOPERATOR = 80;
  public int JJTLTOPERATOR = 81;
  public int JJTGTOPERATOR = 82;
  public int JJTNEOPERATOR = 83;
  public int JJTNEQOPERATOR = 84;
  public int JJTGEOPERATOR = 85;
  public int JJTLEOPERATOR = 86;
  public int JJTLIKEOPERATOR = 87;
  public int JJTLUCENEOPERATOR = 88;
  public int JJTNEAROPERATOR = 89;
  public int JJTWITHINOPERATOR = 90;
  public int JJTSCANDOPERATOR = 91;
  public int JJTCONTAINSKEYOPERATOR = 92;
  public int JJTCONTAINSVALUEOPERATOR = 93;
  public int JJTEQUALSCOMPAREOPERATOR = 94;
  public int JJTRIGHTBINARYCONDITION = 95;
  public int JJTBINARYCONDITION = 96;
  public int JJTCONTAINSVALUECONDITION = 97;
  public int JJTINSTANCEOFCONDITION = 98;
  public int JJTBETWEENCONDITION = 99;
  public int JJTISNULLCONDITION = 100;
  public int JJTISNOTNULLCONDITION = 101;
  public int JJTISDEFINEDCONDITION = 102;
  public int JJTISNOTDEFINEDCONDITION = 103;
  public int JJTCONTAINSCONDITION = 104;
  public int JJTINOPERATOR = 105;
  public int JJTINCONDITION = 106;
  public int JJTNOTINCONDITION = 107;
  public int JJTCONTAINSALLCONDITION = 108;
  public int JJTCONTAINSANYCONDITION = 109;
  public int JJTCONTAINSTEXTCONDITION = 110;
  public int JJTMATCHESCONDITION = 111;
  public int JJTORDERBY = 112;
  public int JJTGROUPBY = 113;
  public int JJTUNWIND = 114;
  public int JJTLIMIT = 115;
  public int JJTSKIP = 116;
  public int JJTBATCH = 117;
  public int JJTTIMEOUT = 118;
  public int JJTWAIT = 119;
  public int JJTRETRY = 120;
  public int JJTCOLLECTION = 121;
  public int JJTFETCHPLAN = 122;
  public int JJTFETCHPLANITEM = 123;
  public int JJTTRAVERSEPROJECTIONITEM = 124;
  public int JJTJSON = 125;
  public int JJTMATCHEXPRESSION = 126;
  public int JJTMATCHPATHITEM = 127;
  public int JJTFIELDMATCHPATHITEM = 128;
  public int JJTMATCHPATHITEMFIRST = 129;
  public int JJTMULTIMATCHPATHITEM = 130;
  public int JJTMULTIMATCHPATHITEMARROWS = 131;
  public int JJTMATCHFILTER = 132;
  public int JJTMATCHFILTERITEM = 133;
  public int JJTOUTPATHITEM = 134;
  public int JJTINPATHITEM = 135;
  public int JJTBOTHPATHITEM = 136;
  public int JJTOUTPATHITEMOPT = 137;
  public int JJTINPATHITEMOPT = 138;
  public int JJTBOTHPATHITEMOPT = 139;
  public int JJTPROFILESTORAGESTATEMENT = 140;
  public int JJTTRUNCATECLASSSTATEMENT = 141;
  public int JJTTRUNCATECLUSTERSTATEMENT = 142;
  public int JJTTRUNCATERECORDSTATEMENT = 143;
  public int JJTFINDREFERENCESSTATEMENT = 144;
  public int JJTCREATECLASSSTATEMENT = 145;
  public int JJTCREATEVIEWSTATEMENT = 146;
  public int JJTALTERCLASSSTATEMENT = 147;
  public int JJTDROPCLASSSTATEMENT = 148;
  public int JJTDROPVIEWSTATEMENT = 149;
  public int JJTIFNOTEXISTS = 150;
  public int JJTCREATEPROPERTYSTATEMENT = 151;
  public int JJTCREATEPROPERTYATTRIBUTESTATEMENT = 152;
  public int JJTALTERPROPERTYSTATEMENT = 153;
  public int JJTDROPPROPERTYSTATEMENT = 154;
  public int JJTCREATEINDEXSTATEMENT = 155;
  public int JJTREBUILDINDEXSTATEMENT = 156;
  public int JJTDROPINDEXSTATEMENT = 157;
  public int JJTCREATECLUSTERSTATEMENT = 158;
  public int JJTALTERCLUSTERSTATEMENT = 159;
  public int JJTDROPCLUSTERSTATEMENT = 160;
  public int JJTALTERDATABASESTATEMENT = 161;
  public int JJTCOMMANDLINEOPTION = 162;
  public int JJTOPTIMIZEDATABASESTATEMENT = 163;
  public int JJTCREATELINKSTATEMENT = 164;
  public int JJTEXPLAINSTATEMENT = 165;
  public int JJTPROFILESTATEMENT = 166;
  public int JJTPERMISSION = 167;
  public int JJTGRANTSTATEMENT = 168;
  public int JJTREVOKESTATEMENT = 169;
  public int JJTCREATEFUNCTIONSTATEMENT = 170;
  public int JJTCREATEUSERSTATEMENT = 171;
  public int JJTDROPUSERSTATEMENT = 172;
  public int JJTALTERROLESTATEMENT = 173;
  public int JJTLETSTATEMENT = 174;
  public int JJTBEGINSTATEMENT = 175;
  public int JJTCOMMITSTATEMENT = 176;
  public int JJTROLLBACKSTATEMENT = 177;
  public int JJTRETURNSTATEMENT = 178;
  public int JJTIFSTATEMENT = 179;
  public int JJTSLEEPSTATEMENT = 180;
  public int JJTCONSOLESTATEMENT = 181;
  public int JJTCREATESEQUENCESTATEMENT = 182;
  public int JJTALTERSEQUENCESTATEMENT = 183;
  public int JJTDROPSEQUENCESTATEMENT = 184;
  public int JJTHASTATUSSTATEMENT = 185;
  public int JJTHAREMOVESERVERSTATEMENT = 186;
  public int JJTHASYNCDATABASESTATEMENT = 187;
  public int JJTHASYNCCLUSTERSTATEMENT = 188;
  public int JJTHASETSTATEMENT = 189;
  public int JJTFOREACHBLOCK = 190;
  public int JJTWHILEBLOCK = 191;
  public int JJTSECURITYRESOURCESEGMENT = 192;
  public int JJTCREATESECURITYPOLICYSTATEMENT = 193;
  public int JJTALTERSECURITYPOLICYSTATEMENT = 194;


  public String[] jjtNodeName = {
    "Rid",
    "parse",
    "parseScript",
    "String",
    "Identifier",
    "Integer",
    "FloatingPoint",
    "Number",
    "Statement",
    "StatementSemicolon",
    "StatementInternal",
    "ExpressionStatement",
    "QueryStatement",
    "SelectWithoutTargetStatement",
    "SelectStatement",
    "TraverseStatement",
    "MatchStatement",
    "DeleteStatement",
    "DeleteVertexStatement",
    "DeleteEdgeStatement",
    "DeleteEdgeByRidStatement",
    "DeleteEdgeFromToStatement",
    "DeleteEdgeToStatement",
    "DeleteEdgeVToStatement",
    "DeleteEdgeWhereStatement",
    "UpdateEdgeStatement",
    "UpdateStatement",
    "UpdateOperations",
    "UpdateItem",
    "UpdateIncrementItem",
    "UpdateRemoveItem",
    "UpdatePutItem",
    "InsertStatement",
    "InsertBody",
    "CreateVertexStatementEmptyNoTarget",
    "CreateVertexStatement",
    "CreateVertexStatementNoTarget",
    "MoveVertexStatement",
    "CreateEdgeStatement",
    "InputParameter",
    "PositionalParameter",
    "NamedParameter",
    "Projection",
    "ProjectionItem",
    "NestedProjection",
    "NestedProjectionItem",
    "ArraySelector",
    "ArrayNumberSelector",
    "ArraySingleValuesSelector",
    "ArrayRangeSelector",
    "Alias",
    "RecordAttribute",
    "FunctionCall",
    "MethodCall",
    "LevelZeroIdentifier",
    "SuffixIdentifier",
    "BaseIdentifier",
    "Modifier",
    "Expression",
    "ArrayConcatExpression",
    "ArrayConcatExpressionElement",
    "MathExpression",
    "FirstLevelExpression",
    "ParenthesisExpression",
    "BaseExpression",
    "FromClause",
    "LetClause",
    "LetItem",
    "FromItem",
    "Cluster",
    "ClusterList",
    "MetadataIdentifier",
    "IndexName",
    "IndexIdentifier",
    "WhereClause",
    "OrBlock",
    "AndBlock",
    "NotBlock",
    "ParenthesisBlock",
    "ConditionBlock",
    "CompareOperator",
    "LtOperator",
    "GtOperator",
    "NeOperator",
    "NeqOperator",
    "GeOperator",
    "LeOperator",
    "LikeOperator",
    "LuceneOperator",
    "NearOperator",
    "WithinOperator",
    "ScAndOperator",
    "ContainsKeyOperator",
    "ContainsValueOperator",
    "EqualsCompareOperator",
    "RightBinaryCondition",
    "BinaryCondition",
    "ContainsValueCondition",
    "InstanceofCondition",
    "BetweenCondition",
    "IsNullCondition",
    "IsNotNullCondition",
    "IsDefinedCondition",
    "IsNotDefinedCondition",
    "ContainsCondition",
    "InOperator",
    "InCondition",
    "NotInCondition",
    "ContainsAllCondition",
    "ContainsAnyCondition",
    "ContainsTextCondition",
    "MatchesCondition",
    "OrderBy",
    "GroupBy",
    "Unwind",
    "Limit",
    "Skip",
    "Batch",
    "Timeout",
    "Wait",
    "Retry",
    "Collection",
    "FetchPlan",
    "FetchPlanItem",
    "TraverseProjectionItem",
    "Json",
    "MatchExpression",
    "MatchPathItem",
    "FieldMatchPathItem",
    "MatchPathItemFirst",
    "MultiMatchPathItem",
    "MultiMatchPathItemArrows",
    "MatchFilter",
    "MatchFilterItem",
    "OutPathItem",
    "InPathItem",
    "BothPathItem",
    "OutPathItemOpt",
    "InPathItemOpt",
    "BothPathItemOpt",
    "ProfileStorageStatement",
    "TruncateClassStatement",
    "TruncateClusterStatement",
    "TruncateRecordStatement",
    "FindReferencesStatement",
    "CreateClassStatement",
    "CreateViewStatement",
    "AlterClassStatement",
    "DropClassStatement",
    "DropViewStatement",
    "IfNotExists",
    "CreatePropertyStatement",
    "CreatePropertyAttributeStatement",
    "AlterPropertyStatement",
    "DropPropertyStatement",
    "CreateIndexStatement",
    "RebuildIndexStatement",
    "DropIndexStatement",
    "CreateClusterStatement",
    "AlterClusterStatement",
    "DropClusterStatement",
    "AlterDatabaseStatement",
    "CommandLineOption",
    "OptimizeDatabaseStatement",
    "CreateLinkStatement",
    "ExplainStatement",
    "ProfileStatement",
    "Permission",
    "GrantStatement",
    "RevokeStatement",
    "CreateFunctionStatement",
    "CreateUserStatement",
    "DropUserStatement",
    "AlterRoleStatement",
    "LetStatement",
    "BeginStatement",
    "CommitStatement",
    "RollbackStatement",
    "ReturnStatement",
    "IfStatement",
    "SleepStatement",
    "ConsoleStatement",
    "CreateSequenceStatement",
    "AlterSequenceStatement",
    "DropSequenceStatement",
    "HaStatusStatement",
    "HaRemoveServerStatement",
    "HaSyncDatabaseStatement",
    "HaSyncClusterStatement",
    "HaSetStatement",
    "ForEachBlock",
    "WhileBlock",
    "SecurityResourceSegment",
    "CreateSecurityPolicyStatement",
    "AlterSecurityPolicyStatement",
  };
}
/* JavaCC - OriginalChecksum=3ae0e1e91de27bf0a3ec1ccddf3905da (do not edit this line) */
