/* Generated By:JJTree: Do not edit this line. OSuffixIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import com.orientechnologies.orient.core.command.OCommandContext;
import com.orientechnologies.orient.core.db.record.OIdentifiable;
import com.orientechnologies.orient.core.record.impl.ODocument;

public class OSuffixIdentifier extends SimpleNode {

  protected OIdentifier      identifier;
  protected ORecordAttribute recordAttribute;
  protected boolean          star = false;

  public OSuffixIdentifier(int id) {
    super(id);
  }

  public OSuffixIdentifier(OrientSql p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  @Override
  public String toString() {
    if (identifier != null) {
      return identifier.toString();
    } else if (recordAttribute != null) {
      return recordAttribute.toString();
    } else if (star) {
      return "*";
    }
    return super.toString();
  }

  public Object execute(OIdentifiable iCurrentRecord, OCommandContext ctx) {
    if (star) {
      return iCurrentRecord;
    }
    if (identifier != null) {
      String varName = identifier.getValue();
      if (ctx.getVariable(varName) != null) {
        return ctx.getVariable(varName);
      }
      return ((ODocument) iCurrentRecord.getRecord()).field(varName);
    }
    if (recordAttribute != null) {
      return ((ODocument) iCurrentRecord.getRecord()).field(recordAttribute.name);
    }
    return null;
  }
}
/* JavaCC - OriginalChecksum=5d9be0188c7d6e2b67d691fb88a518f8 (do not edit this line) */
