/* Generated By:JJTree: Do not edit this line. OUpdateAddItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.Map;

public class OUpdateAddItem extends SimpleNode {

  protected OIdentifier left;
  protected OExpression right;

  public OUpdateAddItem(int id) {
    super(id);
  }

  public OUpdateAddItem(OrientSql p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void replaceParameters(Map<Object, Object> params) {
    right.replaceParameters(params);
  }

  @Override
  public String toString() {
    StringBuilder result = new StringBuilder();
    result.append(left.toString());
    result.append(" = ");
    result.append(value.toString());
    return result.toString();
  }
}
/* JavaCC - OriginalChecksum=769679aa2d2d8df58a13210152b50a9d (do not edit this line) */
