/* Generated By:JJTree: Do not edit this line. OUpdateMergeItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

public
class OUpdateMergeItem extends SimpleNode {
  public OUpdateMergeItem(int id) {
    super(id);
  }

  public OUpdateMergeItem(OrientSql p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2ee108d7d9ceda2c615df09d91f7f40e (do not edit this line) */
